### ISSUE TITLE
Gathering information

### ISSUE THREAD

**Issue by Alexlib2** [Alexlib2/Lab3Repository#1]
Subtask:
- [ ] Analyze domain area
- [ ] Write software requirement specification
- [ ] Draw Use-case diagram
