### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by Alexlib2** [Alexlib2/Lab3Repository#3]
Subtasks:
- [ ] Develop functionality to ask the user, how the function must be calculated.
- [ ] Develop functionality to provide errors and stop the main function from using incorrect data.
- [ ] Develop functionality to ask the user to input new data in case providing wrong data in the first place.
- [ ] Develop functionality to close the program if the user confirms such action.
