### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Alexlib2** [Alexlib2/Lab3Repository#4]
Subtasks:

- [ ] Implement algorithm for calculating the required formula.
- [ ] Implement designed interface.
- [ ] Implement error handling.
